

<!DOCTYPE html>
<html lang="en">
    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta http-equiv="content-type" content="text/html; charset=utf-8">

      <!-- Enable responsiveness on mobile devices-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

      <title>wangbo’s home &amp; blog - Java try-catch and AssertionError</title>

      

      
          <script src="https://cdnjs.cloudflare.com/ajax/libs/slideout/1.0.1/slideout.min.js"></script>
          
      

      
          <link rel="stylesheet" href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;site.css">
          
      

      
      
    </head>

    <body>
        <div class="container">

            <div id="mobile-navbar" class="mobile-navbar">
              <div class="mobile-header-logo">
                <a href="/" class="logo">WB Prime</a>
              </div>
              <div class="mobile-navbar-icon icon-out">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>

            <nav id="mobile-menu" class="mobile-menu slideout-menu slideout-menu-left">
              <ul class="mobile-menu-list">
                
                    <li class="mobile-menu-item">
                        <a href="https://www.wangbo.im">
                            Home
                        </a>
                    </li>
                
                    <li class="mobile-menu-item">
                        <a href="https://www.wangbo.im&#x2F;categories">
                            Categories
                        </a>
                    </li>
                
                    <li class="mobile-menu-item">
                        <a href="https://www.wangbo.im&#x2F;tags">
                            Tags
                        </a>
                    </li>
                
                    <li class="mobile-menu-item">
                        <a href="https://www.wangbo.im&#x2F;about">
                            About
                        </a>
                    </li>
                
                    <li class="mobile-menu-item">
                        <a href="https:&#x2F;&#x2F;github.wangbo.im">
                            Github
                        </a>
                    </li>
                
              </ul>
            </nav>

            <header id="header">
                <div class="logo"><a href="https:&#x2F;&#x2F;www.wangbo.im">WB Prime</a></div>
                <nav class="menu">
                    <ul>
                        
                            <li>
                                <a href="https://www.wangbo.im">
                                    Home
                                </a>
                            </li>
                        
                            <li>
                                <a href="https://www.wangbo.im&#x2F;categories">
                                    Categories
                                </a>
                            </li>
                        
                            <li>
                                <a href="https://www.wangbo.im&#x2F;tags">
                                    Tags
                                </a>
                            </li>
                        
                            <li>
                                <a href="https://www.wangbo.im&#x2F;about">
                                    About
                                </a>
                            </li>
                        
                            <li>
                                <a href="https:&#x2F;&#x2F;github.wangbo.im">
                                    Github
                                </a>
                            </li>
                        
                    </ul>
                </nav>
            </header>

            <main>
                <div class="content" id="mobile-panel">
                    



<article class="post">
    
    <header class="post__header">
        <h1 class="post__title">
            <a href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;posts&#x2F;2019-04-12-java-catch-all-and-assertionerror&#x2F;">Java try-catch and AssertionError</a>
        </h1>
        <div class="post__meta">
            <span class="post__time">2019-04-12</span>
            
        </div>
    </header>

    <div class="post-content">
      <p>Java 的异常处理机制是 try-catch-finally 。被调用的方法或代码块可以抛出异常（Throwable，含 Exception 和 Error）；被调用的方法或代码块被包含在 try 块中；catch 块中会根据具体的异常类型来实现相关的逻辑；finally 块中实现无论是否发生异常都需要的逻辑。</p>
<p>异常处理机制很简单；但是怎么设计异常处理方式是有一些坑的。</p>
<p>有一个线上服务在更新逻辑上线时，触发了一个错误处理异常的 BUG，现简单记录之。</p>
<p><a name="continue-reading"></a></p>
<h1 id="bei-jing"><a class="zola-anchor" href="#bei-jing" aria-label="Anchor link for: bei-jing">🔗</a>
背景</h1>
<p>服务中有一段逻辑：从 DB 中通过 ID 查询任务的描述；任务描述是一个 JSON 格式的字符串，通过一个 type 字段来决定对应的任务实体类型；任务描述根据任务类型被反序列化为不同的任务实体。</p>
<p>相关的逻辑伪代码如下：</p>
<pre style="background-color:#2b303b;">
<span style="color:#c0c5ce;">final Long taskId = 10000L;
</span><span style="color:#c0c5ce;">final Integer taskType = findTaskTypeById(taskId);
</span><span style="color:#c0c5ce;">final String taskStr = findTaskStringById(taskId);
</span><span style="color:#c0c5ce;">switch (taskType) {
</span><span style="color:#c0c5ce;">case 0:
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">TaskV1 taskV1 = parseTaskAsV1(taskStr);
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">// More logic on task v1
</span><span style="color:#c0c5ce;">default:
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">throw new AssertionError(&quot;Unexpected task type &quot; + taskType);
</span><span style="color:#c0c5ce;">}
</span></pre>
<p>当时考虑到任务的类型是静态的：在运行时，对于某个任务类型，服务或者支持或者不支持；如果添加新的任务类型支持，需要开发对应的处理逻辑并重新发布上线；如果在反序列化时遇到了不支持的任务类型，则说明应该是不可恢复的错误。</p>
<p>新的逻辑如下：</p>
<pre style="background-color:#2b303b;">
<span style="color:#c0c5ce;">final Long taskId = 10000L;
</span><span style="color:#c0c5ce;">final Integer taskType = findTaskTypeById(taskId);
</span><span style="color:#c0c5ce;">final String taskStr = findTaskStringById(taskId);
</span><span style="color:#c0c5ce;">switch (taskType) {
</span><span style="color:#c0c5ce;">case 0:
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">TaskV1 taskV1 = parseTaskAsV1(taskStr);
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">// More logic on task v1
</span><span style="color:#c0c5ce;">case 1:
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">TaskV1 taskV2 = parseTaskAsV2(taskStr);
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">// More logic on task v2
</span><span style="color:#c0c5ce;">default:
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">throw new AssertionError(&quot;Unexpected task type &quot; + taskType);
</span><span style="color:#c0c5ce;">}
</span></pre>
<p>对于不支持的任务类型，处理的方式是直接抛出 <code>java.lang.AssertionError</code> 。</p>
<h1 id="bug"><a class="zola-anchor" href="#bug" aria-label="Anchor link for: bug">🔗</a>
BUG</h1>
<p>由于 <code>java.lang.AssertionError</code> 是 <code>java.lang.Error</code> 的子类型，如果没有显式地用 catch 块处理的话，会发生栈回滚导致逻辑中断。</p>
<p>线上服务在一个单独的线程里面执行以上逻辑代码；上述代码抛出 Error 之后外层没有捕获，导致线程退出，使得线程的逻辑中断。</p>
<p>临时通过添加 try-catch Throwable 的代码 fix 了此 BUG。</p>
<h1 id="zong-jie"><a class="zola-anchor" href="#zong-jie" aria-label="Anchor link for: zong-jie">🔗</a>
总结</h1>
<h2 id="error-exception"><a class="zola-anchor" href="#error-exception" aria-label="Anchor link for: error-exception">🔗</a>
Error & Exception</h2>
<p>Java 的异常机制的最顶层的类是 <code>java.lang.Throwable</code>，是 throw 和 catch 能操作的最基本的类型。Throwable 有两个子类，分别代表了不同的错误类型：<code>java.lang.Exception</code> 是程序运行期间内的错误，一般是逻辑错误；<code>java.lang.Error</code> 是程序运行期间 JVM 的错误，一般是系统异常。</p>
<p>按照 JDK 的文档说明，Exception 及其子类是应该被程序代码处理的错误；Error 及其子类不应该被外部代码处理。换言之，在代码的 catch 块中所应该捕获的最顶层错误类型是 Exception，不应该是 Throwable 或 Error。</p>
<p>如果要保持上述惯例，则需要抛出异常时保持相同的管理：不能在程序中抛出 Error 及其子类（更不用说 Throwable），throw 的对象应该是 Exception 或其子类。</p>
<p>理论上，服务代码中不应该与 Error 打交道，不能抛出 (throw) 也不能捕获 (catch) 。</p>
<p>JDK 中对 Exception 的子类型做了区分：受检异常和非受检异常。非受检异常是 <code>java.lang.RuntimeException</code> 及其子类，服务代码中可以抛出也可以捕获；受检异常是不属于非受检异常的 Exception 及其子类。非受检异常和受检异常的区别在于，抛出受检异常的方法或代码块被调用时，必须要捕获（catch 或显式向外传递），非受检异常则不然。</p>
<h2 id="assertionerror"><a class="zola-anchor" href="#assertionerror" aria-label="Anchor link for: assertionerror">🔗</a>
AssertionError</h2>
<p>AssertionError 是 <code>java.lang.Error</code> 的子类型，属于不能在代码中主动抛出和捕获的错误类型。</p>
<h2 id="enum-xiang-guan"><a class="zola-anchor" href="#enum-xiang-guan" aria-label="Anchor link for: enum-xiang-guan">🔗</a>
enum 相关</h2>
<p>对于任务类型类似的场景（可简化为一个 switch-case-default 结构）：根据一个枚举类型（或整型）来分别组织不同的代码逻辑，都需要处理不能识别的类型的逻辑。</p>
<pre style="background-color:#2b303b;">
<span style="color:#c0c5ce;">switch (type) {
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">case 0: /* do somthing here */ break;
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">case 1: /* do somthing here */ break;
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">/* More branches here */
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">default:
</span><span style="color:#c0c5ce;">        </span><span style="color:#c0c5ce;">/* unknown type */ break;
</span><span style="color:#c0c5ce;">}
</span></pre>
<p>如何处理不能识别的类型？</p>
<ul>
<li>策略 1 是简单忽略，即在 default 块中使用空代码，不处理或直接退出。</li>
<li>策略 2 是抛出异常。</li>
</ul>
<p>实际的策略需要分析场景具体制定。对于有确定分类的类型，我倾向于抛出异常。对于异常类型，我之前倾向于使用 AssertionError，现在则倾向于使用 RuntimeException。</p>
<h2 id="uncaughtexceptionhandler"><a class="zola-anchor" href="#uncaughtexceptionhandler" aria-label="Anchor link for: uncaughtexceptionhandler">🔗</a>
UncaughtExceptionHandler</h2>
<p>对于没有捕获的异常，JVM 会调用线程的 uncaughtExceptionHandler 进行处理；如果需要对线程的未捕获的异常做一个最终的处理，需要设置线程的 uncaughtExceptionHandler 或静态的 defaultUncaughtExceptionHandler 。</p>
<pre style="background-color:#2b303b;">
<span style="color:#c0c5ce;">public class Thread {
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">public interface UncaughtExceptionHandler {
</span><span style="color:#c0c5ce;">        </span><span style="color:#c0c5ce;">void uncaughtException(Thread t, Throwable e);
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">}
</span><span style="color:#c0c5ce;">
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">public static void setDefaultUncaughtExceptionHandler(UncaughtExceptionHandler eh) {
</span><span style="color:#c0c5ce;">        </span><span style="color:#c0c5ce;">defaultUncaughtExceptionHandler = eh;
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">}
</span><span style="color:#c0c5ce;">
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">public void setUncaughtExceptionHandler(UncaughtExceptionHandler eh) {
</span><span style="color:#c0c5ce;">        </span><span style="color:#c0c5ce;">uncaughtExceptionHandler = eh;
</span><span style="color:#c0c5ce;">    </span><span style="color:#c0c5ce;">}
</span><span style="color:#c0c5ce;">}
</span></pre><h2 id="result-t-e-in-rust"><a class="zola-anchor" href="#result-t-e-in-rust" aria-label="Anchor link for: result-t-e-in-rust">🔗</a>
Result<T, E> in Rust</h2>
<p>上述的 Error &amp; Exception &amp; RuntimeException 在使用时的区别大部分是语义上的，IDE 和编译器不能帮助开发者严格保持一定的模式。</p>
<p>作为对比，<a href="https://www.rust-lang.org">Rust</a> 里的错误处理机制是基于 <code>Result&lt;T, E&gt;</code> 的。<code>Result&lt;T, E&gt;</code> 是作为方法的返回值存在的，方法被调用时必须要处理错误。Rust 中不存在由于错误没有捕获导致的 BUG （类比 Java 中未捕获 Error 或 RuntimeException）。</p>

    </div>

    
    

    <div class="post-footer">
        
            
                <div class="post-tags">
                    
                        <a href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;tags&#x2F;java&#x2F;">#Java</a>
                    
                        <a href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;tags&#x2F;try-catch&#x2F;">#try-catch</a>
                    
                        <a href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;tags&#x2F;assertionerror&#x2F;">#AssertionError</a>
                    
                </div>
            
            
                <div class="post-nav">
                    
                        <a class="previous" href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;posts&#x2F;2019-03-31-a-bug-introduced-by-optionallong-abuse&#x2F;">‹ 一次由于滥用 OptionalLong.orElse 引发的 BUG</a>
                    
                    
                        <a class="next" href="https:&#x2F;&#x2F;www.wangbo.im&#x2F;posts&#x2F;2019-04-19-communication-bridge-between-webrtc-and-wechat-rtmp&#x2F;">WebRTC 与微信小程序的音视频互通 ›</a>
                    
                    
                    
                </div>
            

        

    </div>

    
    
</article>


                </div>
            </main>

            
            
        </div>

      
          <script type="text/javascript" src="https:&#x2F;&#x2F;www.wangbo.im&#x2F;even.js" ></script>
      
    </body>

</html>
